# This file can be ignored for now but will be used in the future
# for bitbucket pipelines

pipelines:
  branches:
    Master:
      - step:
          name: Build
          runs-on: 
            - 'self.hosted'
          script:
            - ssh -tt $user@$server_ip << EOF
            - cd $BITBUCKET_REPO_SLUG
            - mkdir pipelines-made-this
            - exit
            - EOF
      - step:
          name: Test
          script:
            - echo "This step will run on Atlassian's infrastructure as usual.";
    Staging:
      - step:
          name: Build
          runs-on: 
            - 'self.hosted'
          script:
            - ssh -tt $user@$server_ip << EOF
            - cd $BITBUCKET_REPO_SLUG
            - mkdir pipelines-made-this
            - exit
            - EOF
      - step:
          name: Test
          script:
            - echo "This step will run on Atlassian's infrastructure as usual.";
    
    